-- local lsp_engine = vim.env.NVIM_LSP
-- if (lsp_engine ~= 'coc' && lsp_engine != '') then return end
--
-- local ok, coc = pcall(require, "coc.nvim")
-- if (not ok) then return end
--
-- local remap = vim.api.nvim_set_keymap
-- local setOp = vim.api.nvim_set_option
-- local getOp = vim.api.nvim_get_option
--
-- setOp('encoding', 'utf-8')
-- setOp('hidden', true)
-- setOp('nobackup', true)
-- setOp('nowritebackup', true)
-- setOp('cmdheight', 2)
-- setOp('updatetime', 300)
-- setOp('shortmess', getOp('shortmess')+c)
-- setOp('signcolumn', 'number')
--
